# Generated by Django 4.2 on 2026-07-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancia',
            fields=[
                ('folio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad_reportada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Discrepancia',
                'verbose_name_plural': 'Discrepancias',
                'db_table': 'discrepancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoteMaterial',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caducidad', models.DateField(blank=True, null=True)),
                ('numero_lote_prov', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Lote de material',
                'verbose_name_plural': 'Lotes de material',
                'db_table': 'lote_material',
                'managed': False,
            },
        ),
    ]
