# Generated by Django 4.2 on 2026-07-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisposicionDesecho',
            fields=[
                ('folio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('folio_probatorio', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Disposición de desecho controlado',
                'verbose_name_plural': 'Disposiciones de desecho controlado',
                'db_table': 'disposicion_desecho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisposicionDevolucion',
            fields=[
                ('folio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('motivo_rechazo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Devolución a proveedor',
                'verbose_name_plural': 'Devoluciones a proveedor',
                'db_table': 'disposicion_devolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisposicionReciclaje',
            fields=[
                ('folio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('peso_neto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Disposición de reciclaje',
                'verbose_name_plural': 'Disposiciones de reciclaje',
                'db_table': 'disposicion_reciclaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroDisposicion',
            fields=[
                ('folio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_determinacion', models.DateField()),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('cantidad_ejecutada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Registro de disposición',
                'verbose_name_plural': 'Registros de disposición',
                'db_table': 'registro_disposicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudInspeccion',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField()),
                ('hora_generacion', models.TimeField()),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
                ('hora_atencion', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de inspección',
                'verbose_name_plural': 'Solicitudes de inspección',
                'db_table': 'solicitud_inspeccion',
                'managed': False,
            },
        ),
    ]
