# Generated by Django 4.2 on 2026-07-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_inicial', models.IntegerField()),
                ('cantidad_final', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de producción',
                'verbose_name_plural': 'Órdenes de producción',
                'db_table': 'orden_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroMerma',
            fields=[
                ('folio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField()),
                ('unidad', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Registro de merma',
                'verbose_name_plural': 'Registros de merma',
                'db_table': 'registro_merma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurnoOrden',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_producida', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Turno de orden',
                'verbose_name_plural': 'Turnos de orden',
                'db_table': 'turno_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('orden', models.ForeignKey(db_column='orden', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mermas.ordenproduccion')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto de orden',
                'verbose_name_plural': 'Productos de orden',
                'db_table': 'orden_producto',
                'managed': False,
            },
        ),
    ]
