# Generated by Django 4.2 on 2026-07-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mermas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancia',
            fields=[
                ('folio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('cantidad_reportada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo_reporte', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('motivo_resolucion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'DISCREPANCIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoDiscrepancia',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EDO_DISCREPANCIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoSolicitud',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EDO_SOLICITUD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudInspeccion',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('hora_generacion', models.TimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
                ('hora_atencion', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SOLICITUD_INSPECCION',
                'managed': False,
            },
        ),
    ]
