# Generated by Django 4.2 on 2026-07-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='emNombre', max_length=80)),
                ('primer_apellido', models.CharField(db_column='emPrimerApell', max_length=80)),
                ('segundo_apellido', models.CharField(blank=True, db_column='emSegundoApell', max_length=80, null=True)),
                ('puesto', models.CharField(blank=True, max_length=80, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
