# Generated by Django 4.2 on 2026-07-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Token de acceso',
                'verbose_name_plural': 'Tokens de acceso',
                'db_table': 'usuario_token',
            },
        ),
    ]
