# Generated by Django 4.2 on 2026-07-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaGenerada',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_detectado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Alerta generada',
                'verbose_name_plural': 'Alertas generadas',
                'db_table': 'alerta_generada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UmbralAlerta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Umbral de alerta',
                'verbose_name_plural': 'Umbrales de alerta',
                'db_table': 'umbral_alerta',
                'managed': False,
            },
        ),
    ]
