# Generated by Django 4.2 on 2026-07-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CausaRaiz',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Causa raíz',
                'verbose_name_plural': 'Causas raíz',
                'db_table': 'causa_raiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'db_table': 'componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisposicionFinal',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Disposición final',
                'verbose_name_plural': 'Disposiciones finales',
                'db_table': 'disposicion_final',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoFlujoMerma',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de flujo de merma',
                'verbose_name_plural': 'Estados de flujo de merma',
                'db_table': 'edo_flujo_merma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoSolicitud',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de solicitud',
                'verbose_name_plural': 'Estados de solicitud',
                'db_table': 'edo_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaRecicladora',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa recicladora',
                'verbose_name_plural': 'Empresas recicladoras',
                'db_table': 'empresa_recicladora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstacionTrabajo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('etapa', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estación de trabajo',
                'verbose_name_plural': 'Estaciones de trabajo',
                'db_table': 'estacion_trabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoAlerta',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de alerta',
                'verbose_name_plural': 'Estados de alerta',
                'db_table': 'estado_alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoDisposicion',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de disposición',
                'verbose_name_plural': 'Estados de disposición',
                'db_table': 'estado_disposicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoLinea',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de línea',
                'verbose_name_plural': 'Estados de línea',
                'db_table': 'estado_linea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoLote',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de lote',
                'verbose_name_plural': 'Estados de lote',
                'db_table': 'estado_lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de orden',
                'verbose_name_plural': 'Estados de orden',
                'db_table': 'estado_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadorKpi',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('formula', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Indicador KPI',
                'verbose_name_plural': 'Indicadores KPI',
                'db_table': 'indicador_kpi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_linea', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Línea de producción',
                'verbose_name_plural': 'Líneas de producción',
                'db_table': 'linea_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LineaTurno',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Línea-turno',
                'verbose_name_plural': 'Líneas-turno',
                'db_table': 'linea_turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoDestruccion',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de destrucción',
                'verbose_name_plural': 'Métodos de destrucción',
                'db_table': 'metodo_destruccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='numTel', max_length=20, null=True)),
                ('direccion_calle', models.CharField(blank=True, db_column='dirCalle', max_length=150, null=True)),
                ('direccion_numero', models.CharField(blank=True, db_column='dirNumero', max_length=10, null=True)),
                ('direccion_colonia', models.CharField(blank=True, db_column='dirColonia', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'planta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('pulgadas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_calle', models.CharField(blank=True, db_column='dirCalle', max_length=150, null=True)),
                ('direccion_numero', models.CharField(blank=True, db_column='dirNumero', max_length=10, null=True)),
                ('direccion_colonia', models.CharField(blank=True, db_column='dirColonia', max_length=100, null=True)),
                ('rfc', models.CharField(blank=True, db_column='RFC', max_length=13, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMerma',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de merma',
                'verbose_name_plural': 'Tipos de merma',
                'db_table': 'tipo_merma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdComp',
            fields=[
                ('producto', models.ForeignKey(db_column='producto', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalogos.producto')),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Componente de producto',
                'verbose_name_plural': 'Componentes de producto',
                'db_table': 'prod_comp',
                'managed': False,
            },
        ),
    ]
